throw语句里，类型是静态判断的，当使用

```c++
try
{
throw static_cast<Base*>(new Drived())
}
catch(Drived*)
{
//处理1
}
catch(Base*)
{
//处理2
}
//或者
try
{
    throw static_cast<Base&>(Drived())
}
catch(Drived&)
{
//处理1
}
catch(Base&)
{
//处理2
}
```

都会命中处理2，而不会命中处理1，这在catch中重新抛出时要注意